### ISSUE TITLE
[Bug]: Translation missing keys problem

### ISSUE THREAD

**Issue by sajjadhossainshohagbd** [ElegantEngineeringTech/laravel-translator#5]
### What happened?

When i run php artisan translator:missing en --sync this command. It creates many PHP file in lang folder. 

Screenshot below

![Screenshot 2024-11-30 233810](https://github.com/user-attachments/assets/3727e189-a52a-43f4-90b4-ca0847ca58f8)

### How to reproduce the bug

Don't know.

### Package Version

2.0.2

### PHP Version

8.3

### Laravel Version

11.9

### Which operating systems does with happen with?

Windows

**Comment by sajjadhossainshohagbd** [comment]
Hey @QuentinGab ,

Please look it

**Comment by QuentinGab** [comment]
This is because your are using the PHP driver.

Try using --driver=json 
Or setting up the driver in the config file

**Comment by QuentinGab** [comment]
@sajjadhossainshohagbd

**Comment by sajjadhossainshohagbd** [comment]
@QuentinGab  Oh, got it. Thanks.
