### ISSUE TITLE
[Feature Request] : Command params for Dead translation deletion.

### ISSUE THREAD

**Issue by sajjadhossainshohagbd** [ElegantEngineeringTech/laravel-translator#6]
### What happened?

**

### How to reproduce the bug

**

### Package Version

2.0

### PHP Version

8.3

### Laravel Version

11.x

### Which operating systems does with happen with?

Windows

### Notes

Add support for command-line parameters to identify and delete unused/dead translations from language files. Removing obsolete entries will help keep translation files clean and manageable.

**Comment by sajjadhossainshohagbd** [comment]
Hey @QuentinGab ,

Please review this.

**Comment by QuentinGab** [comment]
Should be available in v2.1.0 using:

`php artisan translator:dead --sync`

Let me know if it doesn't work as expected

**Comment by sajjadhossainshohagbd** [comment]
@QuentinGab 

I see your recent commits, you only added delete method on PHP driver. It will work with json driver?

**Comment by QuentinGab** [comment]
@sajjadhossainshohagbd I haven't tested it, but it should work since this code is not driver-specific. It simply pulls all translation keys, removes the unused ones, and saves the remaining keys.

However, be cautious with this command because it might not detect all translation keys if you're not using standard Laravel methods such as `__`, `@lang`, or `Lang::trans`.

**Comment by sajjadhossainshohagbd** [comment]
@QuentinGab  Understood, I have one idea for auto-translation. Currently, it supports only Openai and Deepl. Both require API keys. But you will integrate Google Translate package, which does not require API keys for auto-translation. I share the package link below.

Package Link :

https://github.com/Stichoza/google-translate-php

**Comment by QuentinGab** [comment]
@sajjadhossainshohagbd 
Actually, I don't think Google Translate is reliable enough to be used at scale for translating websites.
Personally, I only use OpenAI for my translations. I included DeepL because it's fast and commonly included in these types of packages; however, I wouldn't recommend it.

**Comment by QuentinGab** [comment]
You can already really easily use Google translate like this:

In translator.php config file
```php
    'translate' => [
        'service' => MyGoogleTranslateService::class,
    ],
```

**Comment by sajjadhossainshohagbd** [comment]
> @sajjadhossainshohagbd Actually, I don't think Google Translate is reliable enough to be used at scale for translating websites. Personally, I only use OpenAI for my translations. I included DeepL because it's fast and commonly included in these types of packages; however, I wouldn't recommend it.

Yeah, it's true.

**Comment by sajjadhossainshohagbd** [comment]
> You can already really easily use Google translate like this:
> 
> In `translator.php config` file
> 
> ```
>     'translate' => [
>         'service' => MyGoogleTranslateService::class,
>     ],
> ```

Ok, I will try this later.
